apiVersion: v1
kind: Secret
metadata:
  name: istio-gateway-cert
  namespace: istio-system
type: kubernetes.io/tls
annotations:
  cert-manager.io/issuer: "selfsigned-issuer"
  cert-manager.io/common-name: "istio-gateway"
data:
  tls.crt: |
    # This will be populated by cert-manager
    # For production, use proper CA-signed certificates
  tls.key: |
    # This will be populated by cert-manager
    # Private key will be generated automatically# Updated Sun Nov  9 12:50:05 CET 2025
# Updated Sun Nov  9 12:52:18 CET 2025
# Updated Sun Nov  9 12:56:40 CET 2025
