apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod
  namespace: istio-system
automountServiceAccountToken: true# Updated Sun Nov  9 12:50:06 CET 2025
# Updated Sun Nov  9 12:52:18 CET 2025
# Updated Sun Nov  9 12:56:40 CET 2025
